apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env: prod
    owner: opti
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
  - name: {{ .Release.Name }}-mossad-web
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer